// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKk-lxqQBQUj5GSgBVz10b7u-9-kh3CVM',
    appId: '1:872148769295:web:0fbd328aa0fe377f33e17a',
    messagingSenderId: '872148769295',
    projectId: 'shoe-app-f3bbb',
    authDomain: 'shoe-app-f3bbb.firebaseapp.com',
    storageBucket: 'shoe-app-f3bbb.appspot.com',
    measurementId: 'G-01GW8C94H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd5HKJhL0wvbAdPDrfREVLK1tKV96D4SE',
    appId: '1:872148769295:android:dff38c7a7b3e01f933e17a',
    messagingSenderId: '872148769295',
    projectId: 'shoe-app-f3bbb',
    storageBucket: 'shoe-app-f3bbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHfavFBPsMLtzV1pQzuIEwKIl0qE7MphA',
    appId: '1:872148769295:ios:1ffcdcb84bd67bee33e17a',
    messagingSenderId: '872148769295',
    projectId: 'shoe-app-f3bbb',
    storageBucket: 'shoe-app-f3bbb.appspot.com',
    iosBundleId: 'com.example.oxyboots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHfavFBPsMLtzV1pQzuIEwKIl0qE7MphA',
    appId: '1:872148769295:ios:1ffcdcb84bd67bee33e17a',
    messagingSenderId: '872148769295',
    projectId: 'shoe-app-f3bbb',
    storageBucket: 'shoe-app-f3bbb.appspot.com',
    iosBundleId: 'com.example.oxyboots',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKk-lxqQBQUj5GSgBVz10b7u-9-kh3CVM',
    appId: '1:872148769295:web:0a7208174fb07d3133e17a',
    messagingSenderId: '872148769295',
    projectId: 'shoe-app-f3bbb',
    authDomain: 'shoe-app-f3bbb.firebaseapp.com',
    storageBucket: 'shoe-app-f3bbb.appspot.com',
    measurementId: 'G-LYDY491CS1',
  );
}
